### ISSUE TITLE
2 questions about the image caption.

### ISSUE THREAD

**Issue by jiangguoding** [poojahira/image-captioning-bottom-up-top-down#9]
Hi, Pooja: 
     Very glad to read you source code.  It is very well-organised.
     I have 2 Questions: 
         1.  How to get the image file name that corresponds to the generated hypothesis?  when run : python eval.py
         2. Do you have any source code that generate the caption list  when specify a image file?
     (integrate feature extraction/up-down captioning etc  the whole procedure).

    Thanks for your help indeed.

**Comment by poojahira** [comment]
Hi, thanks and sorry for the delay in responding. 
1. You could modify the create_input_files function in utils.py to create a json file with the image file names and then return the file names along with the captions in datasets.py. Else an easy and crude way to find out image file name is to print out the reference captions in eval.py and do a search for one of the captions in the Karpathy json file which will have both image file name and captions associated with them. 
2. Sorry I don't have this and it is a complex functionality because the bottom up features would need to be generated using a faster R-CNN model trained on the visual genome dataset. Such a pretrained model might be available on github though.

**Comment by jiangguoding** [comment]
OK.  Thanks for your response.
